version: "3.8"
services:
  app:
    build: .
    environment:
      DB_HOST: db
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/tmp/cache # ref: https://uraway.hatenablog.com/entry/2019/11/14/130316
    depends_on:
      - redis
      - db
    command: ["bundle", "exec", "foreman", "start", "-f", "Procfile.dev"]
    ports:
      - "3000:3000"
  redis:
    image: redis:alpine
  db: # ref: https://docs.docker.com/compose/rails/
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: tennis_court_agent
      POSTGRES_PASSWORD: tennis_court_agent
